# Generated by Django 5.1.5 on 2025-02-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_faq_answer_bn_faq_answer_hi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_bn',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_hi',
        ),
    ]
